// @generated by protoc-gen-connect-web v0.2.0 with parameter "target=ts"
// @generated from file schema/v1/schema.proto (package schema.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {EventStreamResponse, ResolveBooleanRequest, ResolveBooleanResponse, ResolveFloatRequest, ResolveFloatResponse, ResolveIntRequest, ResolveIntResponse, ResolveObjectRequest, ResolveObjectResponse, ResolveStringRequest, ResolveStringResponse} from "./schema_pb.js";
import {Empty, MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service schema.v1.Service
 */
export const Service = {
  typeName: "schema.v1.Service",
  methods: {
    /**
     * @generated from rpc schema.v1.Service.ResolveBoolean
     */
    resolveBoolean: {
      name: "ResolveBoolean",
      I: ResolveBooleanRequest,
      O: ResolveBooleanResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc schema.v1.Service.ResolveString
     */
    resolveString: {
      name: "ResolveString",
      I: ResolveStringRequest,
      O: ResolveStringResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc schema.v1.Service.ResolveFloat
     */
    resolveFloat: {
      name: "ResolveFloat",
      I: ResolveFloatRequest,
      O: ResolveFloatResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc schema.v1.Service.ResolveInt
     */
    resolveInt: {
      name: "ResolveInt",
      I: ResolveIntRequest,
      O: ResolveIntResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc schema.v1.Service.ResolveObject
     */
    resolveObject: {
      name: "ResolveObject",
      I: ResolveObjectRequest,
      O: ResolveObjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc schema.v1.Service.EventStream
     */
    eventStream: {
      name: "EventStream",
      I: Empty,
      O: EventStreamResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

